name: Build and inspect React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs.on: ubuntu-22.04

    steps:
      - name: Checkout the app
      - uses: actions/checkout@v2

      - name: Hello world
      - run: npm i